networks:
  public:
    external: true
    name: public
services:
  opentripplanner:
    deploy:
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: Host:api.angermuende.bbnavi.de,api.bbnavi.de
        traefik.port: '8080'
      placement:
        constraints:
        - node.hostname == node-001.tpwd-bb-navi
      replicas: 1
    environment:
      API_URL: https://api-bbnavi.docker.localhost
      CONFIG: bb_angermuende
      DT_IMAGE: bb-navi/digitransit-ui
      DT_TAG: next
      GEOCODING_BASE_URL: https://photon.stadtnavi.eu/pelias/v1
      GRAPH_BUILD_MEMORY: 5G
      GTFS_URL: https://www.openvvs.de/dataset/e66f03e4-79f2-41d0-90f1-166ca609e491/resource/bfbb59c7-767c-4bca-bbb2-d8d32a3e0378/download/google_transit.zip
      OSM_URL: https://download.geofabrik.de/europe/germany/brandenburg-latest.osm.pbf
      OTP_IMAGE: mfdz/opentripplanner
      OTP_PORT: '8090'
      OTP_TAG: latest
      ROUTER: bb_angermuende
    healthcheck:
      interval: 15s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://localhost:8080/
      timeout: 10s
    image: registry.gitlab.tpwd.de/tpwd/bb-navi/opentripplaner-berlin-brandenburg:production
    networks:
      public: {}
version: '3.7'

