version: '3.7'


services:
  opentripplanner:
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == node-001.tpwd-bb-navi
      labels:
        traefik.docker.network: public
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: Host:api.tpwd-bb-navi.customer.planetary-quantum.net
        traefik.port: '8080'
